# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170727_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
