# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20170729_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
